spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/rest
        username: postgres
        password: Urmat0204

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

server:
    port: 8181